In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
car = pd.read_csv(r'D:\20\Car details v3.csv')

In [3]:
car.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [4]:
car.tail()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [5]:
car.info()

<class 'pandas.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   str
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   str
 5   seller_type    8128 non-null   str
 6   transmission   8128 non-null   str
 7   owner          8128 non-null   str
 8   mileage        7907 non-null   str
 9   engine         7907 non-null   str
 10  max_power      7913 non-null   str
 11  torque         7906 non-null   str
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), str(9)
memory usage: 825.6 KB

In [7]:
round(car.describe(), 2)

          year  selling_price   km_driven    seats
count  8128.00        8128.00     8128.00  7907.00
mean   2013.80      638271.81    69819.51     5.42
std       4.04      806253.40    56550.55     0.96
min    1983.00       29999.00        1.00     2.00
25%    2011.00      254999.00    35000.00     5.00
50%    2015.00      450000.00    60000.00     5.00
75%    2017.00      675000.00    98000.00     5.00
max    2020.00    10000000.00  2360457.00    14.00

In [8]:
car['selling_price'].unique()

array([  450000,   370000,   158000,   225000,   130000,   440000,
          96000,    45000,   350000,   200000,   500000,    92000,
         280000,   180000,   400000,   778000,   150000,   680000,
         174000,   950000,   525000,   600000,   575000,   275000,
         300000,   220000,   254999,   670000,    70000,   730000,
         650000,   330000,   366000,  1149000,   425000,  2100000,
         925000,   675000,   819999,   390000,  1500000,   700000,
        1450000,  1090000,   850000,  1650000,  1750000,  1590000,
        1689999,  1425000,   265000,   190000,   630000,   540000,
         448000,   745000,  1025000,   235000,  1700000,    50000,
        1200000,   610000,  2500000,   484999,   315000,   475000,
         290000,   455000,   351000,   535000,   175000,   565000,
         120000,   725000,   185000,   615000,   270000,   625000,
         866000,   375000,   522000,   451999,   780000,   595000,
        1140000,   360000,   105000,   135000,   690000,  3975000,
        5150000,  3200000,  4100000,  4500000,  6000000,  3790000,
        2150000,  5800000,  1864999,  2700000,   795000,  3400000,
        2650000,  5850000,   975000,   805000,  2625000,   811000,
         550000,   645000,  2550000,   599000,   875000,   894999,
         340000,  1525000,  1900000,  2900000, 10000000,   160000,
         515000,    40000,   480000,   487000,   386000,   100000,
         490000,   345000,    85000,   215000,   320000,   459999,
          65000,   720000,   800000,   520000,   580000,   420000,
        1250000,   830000,   335000,   329000,   775000,   524000,
         245000,   910000,   900000,   250000,  1100000,   640000,
         409999,   165000,    80000,  1000000,   110000,    75000,
         170000,  1380000,  1300000,   530000,   310000,  1150000,
         380000,   404000,   114999,   465000,   210000,  4600000,
         509999,    90000,   409000,   395000,    81000,   555000,
         229999,  1210000,   325000,    60000,    89000,   434999,
        3000000,   570000,  1550000,    64000,   140000,   503000,
        3800000,  2000000,   740000,   750000,  5400000,  5500000,
         779000,  2475000,   240000,  1085000,    95000,  1290000,
         219000,   260000,   840000,   292000,   385000,  1050000,
         735000,   560000,   585000,   760000,   430000,   643000,
         285000,   660000,   268000,    88000,   561000,   755000,
         125000,  1600000,   801000,   317000,   495000,   236000,
        1800000,   415000,   217000,   466000,   204999,   605000,
        1350000,   337000,   655000,   196000,   299000,   634000,
        1225000,   238000,    72000,   590000,   195000,   715000,
         168000,   531000,  1625000,   145000,   441000,    67500,
         321000,   298000,  1075000,   681000,   810000,   573000,
         101000,  1019999,   244000,  1165000,   241000,   327000,
         620000,   576000,   695000,   231000,   261000,   371000,
         421000,   710000,  1040000,   199000,   305000,  1745000,
         611000,    55000,  1325000,   885000,   108000,   272000,
        1125000,   388000,   757000,   626000,   793000,  3750000,
        1400000,  1925000,   844999,  2940000,  1825000,   890000,
         770000,   467000,   711000,   511000,   163000,   166000,
         392000,   833000,    35000,   880000,  1030000,   521000,
         451000,   472000,   649000,   429000,  1576000,   825000,
         470000,  1560000,  1950000,   786000,   731000,   191000,
         651000,   589000,   445000,    93150,   403000,   144000,
          52000,   302000,   869999,   155000,   246000,   405000,
        3250000,  1143000,   635000,  1575000,   318000,   152000,
         248000,  1465000,  1080000,   678000,  1460000,   756000,
         665000,  2950000,   377000,  1675000,   169000,   685000,
         749000,   899000,   259000,   416000,   773000,   889000,
         118000,   256000,  1888000,    99000,  2280000,    31504,
         295000,   444000,    93000,   860000,  2450000,   198000,
        2825000,  2125000,  3350000,   365000,   919999,  2600000,
         839000,  1594000,   161000,   423000,   551000,   127000,
         411000,  1530000,   376000,  1850000,    86000,   822000,
          30000,   252000,   131000,   128000,   790000,   604000,
        1175000,   256999,   141000,   151000,   577000,    83000,
         946000,   356000,   955000,   978999,   348000,   399000,
         362000,   499000,   358000,   278000,   426000,   211000,
        1270000,   426999,   960000,  1031000,   479000,   764000,
        2199000,  3600000,   184000,   119000,   267000,   328000,
         112999,    39000,  2850000,  2800000,  3900000,   221000,
         631000,   308000,   940000,   361000,   355000,  7200000,
         930000,  1670000,   980000,   486000,   242000,   654000,
         835000,   408000,    94500,  1110000,   438999,   911999,
         693000,   449000,  1390000,   698000,   539000,   765000,
         562000,   571000,   227999,  1151000,  1295000,  4090000,
         347000,   493000,    78000,   545000,  1475000,   287000,
        1630000,   501000,   181000,  2711000,  1035000,   316000,
         813000,  1190000,   378000,   156000,   194000,   754000,
          55599,  1511000,   250999,   312000,    66000,   369000,
         149000,   752000,   142000,   111000,   206000,   567000,
         699000,   632000,   905000,  1145000,    33983,    58000,
         179000,  1515000,   178000,   222000,   387000,  1405000,
         282000,   458000,   157000,   497000,  1227000,   574000,
         121000,  3100000,    68000,  1920000,   808000,   512000,
         671000,   799000,  1365000,  1490000,    80500,   189000,
         892000,  1680000,   667000,   204000,    42000,   694000,
         861999,   476999,  5200000,  2375000,  2750000,  1385000,
         785000,  1275000,  1748999,   132000,    33351,  2064000,
         469000,   906000,   797000,  6223000,  5923000,  6523000,
         122000,   891000,   346000,   532000,   974000,   483000,
         138000,   432000,  1757000,   412000,   126000,   736000,
         579000,   187000,  4000000,  1898999,   311000,   482000,
         401000,   737000,   291000,   999000,   957000,   834000,
         297000,   669000,   616000,   129000,   115999,   861000,
        3251000,   911000,   148000,   433000,   488000,    67000,
         516000,   136000,    29999,   124000,  1938000,   172000,
          59000,  3500000,   537000,    56000,   849000,   851000,
         597000,   741000,   556000,   549000,   679000,   969999,
        1237000,    31000,   666000,    54000,   374000,   455999,
         453000,   258000,   428000,   262000,   389000,   339000,
         277000,   578000,   684000,   949000,   227000,  5830000,
         721000,   751000,  2400000,   990000,  1282000,  1147000,
         558000,   722000,   563000,  2300000,  2200000,    57000,
         488999,   276000,   434000,   372000,  1520000,   202999,
         541000,   254000,   528000,   102000,   977000,  1251000,
        1445000,    98000,    59259,   153000,  1051000,   591000,
         319000,   454000,  1160000,  3300000,   791000,   352000,
         802999,  1789999,  1044999,   279000,   944999,  1859000,
         624000,  2175000,   430999,   803999,   934000,   357000,
         965000,   341000,    75527,  1132000,   252999,   313000,
         391000,  2051000,   212000,  2575000,  1516000,   359000,
         209000,  1220000,  1180000,    45957,  1265000,   382000,
         526000,    90177,    46000,   307000,   746000])

In [9]:
car['selling_price'].nunique()

677

In [10]:
car['selling_price'].value_counts()

selling_price
300000    227
600000    213
350000    209
550000    204
450000    195
         ...
526000      1
90177       1
46000       1
307000      1
746000      1
Name: count, Length: 677, dtype: int64

In [11]:
car['engine'].str.split()

0       [1248, CC]
1       [1498, CC]
2       [1497, CC]
3       [1396, CC]
4       [1298, CC]
           ...
8123    [1197, CC]
8124    [1493, CC]
8125    [1248, CC]
8126    [1396, CC]
8127    [1396, CC]
Name: engine, Length: 8128, dtype: object

In [12]:
car['engine'].str.split('8')

0       [124,  CC]
1       [149,  CC]
2        [1497 CC]
3        [1396 CC]
4       [129,  CC]
           ...
8123     [1197 CC]
8124     [1493 CC]
8125    [124,  CC]
8126     [1396 CC]
8127     [1396 CC]
Name: engine, Length: 8128, dtype: object

In [13]:
car['engine'].str.split(expand=True)

         0   1
0     1248  CC
1     1498  CC
2     1497  CC
3     1396  CC
4     1298  CC
...    ...  ..
8123  1197  CC
8124  1493  CC
8125  1248  CC
8126  1396  CC
8127  1396  CC

[8128 rows x 2 columns]

In [36]:
car = pd.read_csv(r'D:\20\Car details v3.csv')

car[['engine', 'engine_unit']] = car['engine'].str.split(expand=True)
car['engine'].head()

0    1248
1    1498
2    1497
3    1396
4    1298
Name: engine, dtype: str

In [38]:
car['engine'] = car['engine'].astype('float32')
car['engine'].head()

0    1248.0
1    1498.0
2    1497.0
3    1396.0
4    1298.0
Name: engine, dtype: float32

In [39]:
car['engine_unit'].unique()

<StringArray>
['CC', nan]
Length: 2, dtype: str

In [40]:
car.drop('engine_unit', axis=1, inplace = True)

In [41]:
car[['max_power', 'max_power_unit']] = car['max_power'].str.split(expand=True)

In [42]:
car['max_power'].head()

0        74
1    103.52
2        78
3        90
4      88.2
Name: max_power, dtype: str

In [30]:
car['max_power'] = car['max_power'].astype('float32')

ValueError: could not convert string to float: 'bhp'

In [32]:
car[car['max_power'] == 'bhp']

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,max_power_unit
4933,Maruti Omni CNG,2000,80000,100000,CNG,Individual,Manual,Second Owner,10.9 km/kg,796.0,bhp,NaN,8.0,NaN

In [45]:
def isFloat(value) :
    try :
        num = float(value)
        return num
    except ValueError :
        return np.nan

In [46]:
car['max_power'] = car['max_power'].apply(isFloat)
car['max_power_unit'].unique()

<StringArray>
['bhp', nan]
Length: 2, dtype: str

In [47]:
car.drop('max_power_unit', axis=1, inplace=True)

In [48]:
car['max_power'].head(10)

0     74.00
1    103.52
2     78.00
3     90.00
4     88.20
5     81.86
6     57.50
7     37.00
8     67.10
9     68.10
Name: max_power, dtype: float64

In [49]:
car[['mileage', 'mileage_unit']] = car['mileage'].str.split(expand=True)

In [50]:
car['mileage'] = car['mileage'].astype('float32')
car['mileage_unit'].unique()

<StringArray>
['kmpl', 'km/kg', nan]
Length: 3, dtype: str

In [51]:
car['fuel'].unique()

<StringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str

In [52]:
def mile(x) :
    if x['fuel']  == 'Petrol' :
        return x['mileage'] / 80.43
    
    elif x['fuel'] == 'Diesel' :
        return x['mileage'] / 73.56
    
    elif x['fuel'] == 'LPG' :
        return x['mileage'] / 40.85
    
    else :
        return x['mileage'] /44.23

In [53]:
car['mileage'] = car.apply(mile, axis=1)

In [54]:
car.drop('mileage_unit', axis=1, inplace=True)

In [55]:
car['torque'].head()

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: str

In [56]:
car['torque'] = car['torque'].str.upper()

In [57]:
def torque_unit(x) :
    if 'NM' in str(x) :
        return 'Nm'
    
    elif 'KGM' in str(x) :
        return 'kgm'

In [58]:
car['torque_unit'] = car['torque'].apply(torque_unit)
car['torque_unit'].unique()

<StringArray>
['Nm', 'kgm', nan]
Length: 3, dtype: str

In [59]:
car['torque_unit'].isna()
car[car['torque_unit'].isna()]
car[car['torque_unit'].isna()]['torque'].unique()

<StringArray>
[nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800', '210 / 1900']
Length: 5, dtype: str

In [60]:
car['torque_unit'].fillna('Nm', inplace=True)

C:\Users\asia\AppData\Local\Temp\ipykernel_15456\2834636657.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  car['torque_unit'].fillna('Nm', inplace=True)

0        Nm
1        Nm
2       kgm
3       kgm
4       kgm
       ...
8123     Nm
8124    kgm
8125     Nm
8126     Nm
8127     Nm
Name: torque_unit, Length: 8128, dtype: str

In [61]:
string_example = '12.7@ 2,700(KGM@ RPM)'

In [62]:
string_example[:4]

'12.7'

In [63]:
for i, j in enumerate(string_example) :
    print(i, '번째 텍스트: ', j)

0 번째 텍스트:  1
1 번째 텍스트:  2
2 번째 텍스트:  .
3 번째 텍스트:  7
4 번째 텍스트:  @
5 번째 텍스트:
6 번째 텍스트:  2
7 번째 텍스트:  ,
8 번째 텍스트:  7
9 번째 텍스트:  0
10 번째 텍스트:  0
11 번째 텍스트:  (
12 번째 텍스트:  K
13 번째 텍스트:  G
14 번째 텍스트:  M
15 번째 텍스트:  @
16 번째 텍스트:
17 번째 텍스트:  R
18 번째 텍스트:  P
19 번째 텍스트:  M
20 번째 텍스트:  )

In [64]:
for i, j in enumerate(string_example) :
    if j not in '0123456789. ' :
        cut = i
        break

In [65]:
def split_num(x) :
    x = str(x)
    for i, j in enumerate(x) :
        if j not in '0123456789. ' :
            cut = i
            break
    return x[:cut]

In [66]:
car['torque'] = car['torque'].apply(split_num)
car['torque']

0         190
1         250
2        12.7
3       22.4
4        11.5
        ...
8123    113.7
8124       24
8125      190
8126      140
8127      140
Name: torque, Length: 8128, dtype: str

In [67]:
car['torque'] = car['torque'].astype('float64')

ValueError: could not convert string to float: ''

In [69]:
car['torque'] = car['torque'].replace('', np.nan)

In [70]:
car['torque'] = car['torque'].astype('float64')

In [71]:
car['torque'].head()

0    190.0
1    250.0
2     12.7
3     22.4
4     11.5
Name: torque, dtype: float64

In [72]:
def torque_trans(x) :
    if x['torque_unit'] == 'kgm' :
        return x['torque'] * 9.8066
    
    else :
        return x['torque']

In [73]:
car['torque'] = car.apply(torque_trans, axis=1)

In [75]:
car.drop('torque_unit', axis=1, inplace=True)

In [76]:
car.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,0.318108,1248.0,74.00,190.00000,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,0.287384,1498.0,103.52,250.00000,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,0.220067,1497.0,78.00,124.54382,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,0.312670,1396.0,90.00,219.66784,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,0.200174,1298.0,88.20,112.77590,5.0

In [77]:
car['name'] = car['name'].str.split(expand=True)[0]

In [78]:
car['name'].unique()

<StringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',          'Fiat',        'Datsun',
          'Jeep', 'Mercedes-Benz',    'Mitsubishi',          'Audi',
    'Volkswagen',           'BMW',        'Nissan',         'Lexus',
        'Jaguar',          'Land',            'MG',         'Volvo',
        'Daewoo',           'Kia',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel',       'Peugeot']
Length: 32, dtype: str

In [79]:
car['name'] = car['name'].replace('Land', "Land Rover")

In [80]:
car.dropna(inplace=True)
len(car)

7906

In [81]:
car = pd.get_dummies(car, columns = ['name', 'fuel', 'seller_type', 
                                     'transmission', 'owner'], drop_first=True)

car.head()

,year,selling_price,km_driven,mileage,engine,max_power,torque,seats,name_Ashok,name_Audi,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2014,450000,145500,0.318108,1248.0,74.00,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
1,2014,370000,120000,0.287384,1498.0,103.52,250.00000,5.0,False,False,...,True,False,False,True,False,True,False,True,False,False
2,2006,158000,140000,0.220067,1497.0,78.00,124.54382,5.0,False,False,...,False,False,True,True,False,True,False,False,False,True
3,2010,225000,127000,0.312670,1396.0,90.00,219.66784,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
4,2007,130000,120000,0.200174,1298.0,88.20,112.77590,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False

In [82]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(car.drop(
    'selling_price', axis=1), car['selling_price'], test_size=0.2, random_state=100)

In [83]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=100)

model.fit(X_train, y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [84]:
from sklearn.metrics import mean_squared_error

print('train_rmse:', mean_squared_error(y_train, train_pred) ** 0.5,
      'test_rmse:', mean_squared_error(y_test, test_pred) ** 0.5)

train_rmse: 53531.41548125947 test_rmse: 131855.18391308116

In [85]:
from sklearn.model_selection import KFold

car

,year,selling_price,km_driven,mileage,engine,max_power,torque,seats,name_Ashok,name_Audi,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2014,450000,145500,0.318108,1248.0,74.00,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
1,2014,370000,120000,0.287384,1498.0,103.52,250.00000,5.0,False,False,...,True,False,False,True,False,True,False,True,False,False
2,2006,158000,140000,0.220067,1497.0,78.00,124.54382,5.0,False,False,...,False,False,True,True,False,True,False,False,False,True
3,2010,225000,127000,0.312670,1396.0,90.00,219.66784,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
4,2007,130000,120000,0.200174,1298.0,88.20,112.77590,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,2013,320000,110000,0.230014,1197.0,82.85,113.70000,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
8124,2007,135000,119000,0.228385,1493.0,110.00,235.35840,5.0,False,False,...,True,False,False,True,False,True,True,False,False,False
8125,2009,382000,120000,0.262371,1248.0,73.90,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
8126,2013,290000,25000,0.320419,1396.0,70.00,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
8127,2013,290000,25000,0.320419,1396.0,70.00,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False

In [86]:
car.reset_index(drop=True, inplace=True)
car

,year,selling_price,km_driven,mileage,engine,max_power,torque,seats,name_Ashok,name_Audi,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2014,450000,145500,0.318108,1248.0,74.00,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
1,2014,370000,120000,0.287384,1498.0,103.52,250.00000,5.0,False,False,...,True,False,False,True,False,True,False,True,False,False
2,2006,158000,140000,0.220067,1497.0,78.00,124.54382,5.0,False,False,...,False,False,True,True,False,True,False,False,False,True
3,2010,225000,127000,0.312670,1396.0,90.00,219.66784,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
4,2007,130000,120000,0.200174,1298.0,88.20,112.77590,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,2013,320000,110000,0.230014,1197.0,82.85,113.70000,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
7902,2007,135000,119000,0.228385,1493.0,110.00,235.35840,5.0,False,False,...,True,False,False,True,False,True,True,False,False,False
7903,2009,382000,120000,0.262371,1248.0,73.90,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
7904,2013,290000,25000,0.320419,1396.0,70.00,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
7905,2013,290000,25000,0.320419,1396.0,70.00,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False

In [88]:
kf = KFold(n_splits=5)

X = car.drop('selling_price', axis=1)
y = car['selling_price']

In [89]:
for i, j in kf.split(X) :
    print(i, j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]

In [90]:
for train_index, test_index in kf.split(X) :
    
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [91]:
train_rmse_total = []
test_rmse_total = []

for train_index, test_index in kf.split(X) :
    X_train, X_test, = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(random_state=100)
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse = mean_squared_error(y_train, train_pred) ** 0.5
    test_rmse = mean_squared_error(y_test, test_pred) ** 0.5
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)
    
    train_rmse_total

In [ ]:
print('train_rmse: ', sum(train_rmse_total)/ 5, 
      'test_rmse: ', sum(test_rmse_total) /5)

train_rmse:  56553.836119114814 test_rmse:  142936.5891824404

In [94]:
train_rmse_total = []
test_rmse_total = []

for train_index, test_index in kf.split(X) :
    
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(n_estimators= 300, 
                                  max_depth=50, 
                                  min_samples_split=5,
                                  min_samples_leaf=1, n_jobs= -1,
                                  random_state=100)
    
    model.fit(X_train, y_train)
    
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse = mean_squared_error(y_train, train_pred) ** 0.5
    test_rmse = mean_squared_error(y_test, test_pred) ** 0.5
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)
    
    print('train_rmse: ', sum(train_rmse_total) / 5, 
          "test_rmse: ", sum(test_rmse_total) / 5)

train_rmse:  12429.163362149735 test_rmse:  32831.76798954283
train_rmse:  26512.169969754537 test_rmse:  59325.50266253911
train_rmse:  39677.425303726006 test_rmse:  83676.79314980499
train_rmse:  53056.62042741971 test_rmse:  113508.0624147711
train_rmse:  66762.84568886801 test_rmse:  142205.8344141466